# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import loyalty as module_0


def test_case_0():
    int_0 = -10
    int_1 = 1000
    with pytest.raises(ValueError):
        module_0.award_points(int_0, int_1)


def test_case_1():
    int_0 = 0
    int_1 = 100
    int_2 = module_0.award_points(int_0, int_1)
    assert int_2 == 0
    assert module_0.VIP_THRESHOLD_PLN == 5000
    assert module_0.POINTS_CAP == 5000


def test_case_2():
    int_0 = 100
    int_1 = -1000
    with pytest.raises(ValueError):
        module_0.award_points(int_0, int_1)


def test_case_3():
    int_0 = 100
    int_1 = 5100
    int_2 = module_0.award_points(int_0, int_1)
    assert int_2 == 20
    assert module_0.VIP_THRESHOLD_PLN == 5000
    assert module_0.POINTS_CAP == 5000


def test_case_4():
    int_0 = 60000
    int_1 = 100
    int_2 = module_0.award_points(int_0, int_1)
    assert int_2 == 5000
    assert module_0.VIP_THRESHOLD_PLN == 5000
