# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import invoice as module_0


def test_case_0():
    str_0 = 'W"Oht'
    with pytest.raises(ValueError):
        module_0.parse_invoice_id(str_0)


def test_case_1():
    str_0 = "Z&Ou"
    with pytest.raises(ValueError):
        module_0.parse_invoice_id(str_0)


def test_case_2():
    str_0 = 'W"Oht'
    with pytest.raises(ValueError):
        module_0.parse_invoice_id(str_0)


def test_case_3():
    str_0 = "r68"
    with pytest.raises(ValueError):
        module_0.parse_invoice_id(str_0)
