# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import invoice as module_0


def test_case_0():
    str_0 = "l_UIV5~J;Tz>7"
    with pytest.raises(ValueError):
        module_0.parse_invoice_id(str_0)


def test_case_1():
    str_0 = "FV/2026/09/0000"
    with pytest.raises(ValueError):
        module_0.parse_invoice_id(str_0)


def test_case_2():
    str_0 = "FV/1999/12/0000"
    with pytest.raises(ValueError):
        module_0.parse_invoice_id(str_0)


def test_case_3():
    str_0 = "  \tFV/2026/09/0042 \n"
    module_0.parse_invoice_id(str_0)
