# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import loyalty as module_0


def test_case_0():
    float_0 = 127.19
    int_0 = module_0.award_points(float_0, float_0)
    assert int_0 == 12
    assert module_0.VIP_THRESHOLD_PLN == 5000
    assert module_0.POINTS_CAP == 5000
