# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import invoice as module_0


def test_case_0():
    str_0 = "FV/2020/05/0000"
    with pytest.raises(ValueError):
        module_0.parse_invoice_id(str_0)


def test_case_1():
    str_0 = "^FV/(\\d{4})/(0[1-9]|1[0-2])/(\\d{4})$"
    with pytest.raises(ValueError):
        module_0.parse_invoice_id(str_0)


def test_case_2():
    str_0 = "FV/2020/01/0000"
    with pytest.raises(ValueError):
        module_0.parse_invoice_id(str_0)


def test_case_3():
    str_0 = " \t\nFV/2001/02/0001 \n"
    module_0.parse_invoice_id(str_0)


def test_case_4():
    str_0 = "FV/1999/05/0000"
    with pytest.raises(ValueError):
        module_0.parse_invoice_id(str_0)
