# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import loyalty as module_0


def test_case_0():
    float_0 = 1716.363
    int_0 = module_0.award_points(float_0, float_0)
    assert int_0 == 171
    assert module_0.VIP_THRESHOLD_PLN == 5000
    assert module_0.POINTS_CAP == 5000
    int_1 = -1702
    float_1 = 3061.1811
    with pytest.raises(ValueError):
        module_0.award_points(int_1, float_1)


def test_case_1():
    int_0 = 321
    float_0 = 36263.0
    int_1 = module_0.award_points(float_0, float_0)
    assert int_1 == 5000
    assert module_0.VIP_THRESHOLD_PLN == 5000
    int_2 = module_0.award_points(int_0, int_0)
    assert int_2 == 32
    bool_0 = False
    int_3 = module_0.award_points(bool_0, int_1)
    assert int_3 == 0


def test_case_2():
    int_0 = 321
    bool_0 = True
    int_1 = module_0.award_points(int_0, bool_0)
    assert int_1 == 32
    assert module_0.VIP_THRESHOLD_PLN == 5000
    assert module_0.POINTS_CAP == 5000
    float_0 = 3496.013008487928
    int_2 = module_0.award_points(float_0, float_0)
    bool_1 = False
    int_3 = module_0.award_points(bool_1, int_2)
    assert int_3 == 0
    int_4 = 4377
    int_5 = module_0.award_points(int_4, int_3)
    assert int_5 == 437
    float_1 = -1528.5187407844714
    with pytest.raises(ValueError):
        module_0.award_points(int_0, float_1)
