# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import loyalty as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -10
    int_1 = 1000
    int_2 = module_0.award_points(int_0, int_1)


def test_case_1():
    int_0 = 0
    int_1 = 1000
    int_2 = module_0.award_points(int_0, int_1)
    assert int_2 == 0


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 100
    int_1 = -500
    int_2 = module_0.award_points(int_0, int_1)


def test_case_3():
    int_0 = 1000
    int_1 = 6000
    int_2 = module_0.award_points(int_0, int_1)
    assert int_2 is None
