# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import invoice as module_0


def test_case_0():
    str_0 = "FV/2000/01/0001"
    dict_0 = module_0.parse_invoice_id(str_0)
    assert dict_0 is None


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "FV2026/09/0042"
    dict_0 = module_0.parse_invoice_id(str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "FV/1999/12/0042"
    dict_0 = module_0.parse_invoice_id(str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "FV/2026/09/0000"
    dict_0 = module_0.parse_invoice_id(str_0)
