# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import loyalty as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -10
    int_1 = 0
    int_2 = module_0.award_points(int_0, int_1)


def test_case_1():
    float_0 = 9.99
    int_0 = 1000
    int_1 = module_0.award_points(float_0, int_0)
    assert int_1 == 0
    int_2 = 0
    int_3 = module_0.award_points(int_2, int_0)
    assert int_3 == 0


def test_case_2():
    int_0 = 10
    int_1 = 5000
    int_2 = module_0.award_points(int_0, int_1)
    int_3 = 2
    var_0 = int_2 == int_3
    assert var_0 is True
    float_0 = 4999.99
    int_4 = module_0.award_points(int_0, float_0)
    int_5 = 1
    var_1 = int_4 == int_5
    assert var_1 is True
    float_1 = 5000.01
    int_6 = module_0.award_points(int_0, float_1)
