# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import loyalty as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -10
    int_1 = 0
    int_2 = module_0.award_points(int_0, int_1)


def test_case_1():
    int_0 = 250000
    int_1 = 0
    int_2 = module_0.award_points(int_0, int_1)
    int_3 = 5000
    var_0 = int_2 == int_3
    assert var_0 is True


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    int_0 = module_0.award_points(bool_0, bool_0)
    assert int_0 == 0
    int_1 = module_0.award_points(int_0, bool_0)
    assert int_1 == 0
    float_0 = 807.22837
    bool_1 = True
    bool_2 = False
    bool_3 = True
    int_2 = module_0.award_points(float_0, bool_3)
    assert int_2 == 80
    int_3 = module_0.award_points(bool_1, bool_2)
    assert int_3 == 0
    int_4 = -2233
    int_5 = module_0.award_points(float_0, int_4)


def test_case_3():
    int_0 = 5000
    int_1 = 35
    int_2 = module_0.award_points(int_1, int_0)
    int_3 = 8
    var_0 = int_2 == int_3
    assert var_0 is True
    int_4 = 26
    int_5 = 5100
    int_6 = module_0.award_points(int_4, int_5)
