# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import loyalty as module_0


def test_case_0():
    int_0 = -1
    int_1 = 1000
    with pytest.raises(ValueError):
        module_0.award_points(int_0, int_1)


def test_case_1():
    float_0 = 0.0
    float_1 = 1000.0
    int_0 = module_0.award_points(float_0, float_1)
    assert int_0 == 0
    assert module_0.VIP_THRESHOLD_PLN == 5000
    assert module_0.POINTS_CAP == 5000


def test_case_2():
    int_0 = 100
    int_1 = -1
    with pytest.raises(ValueError):
        module_0.award_points(int_0, int_1)


def test_case_3():
    float_0 = 100.0
    float_1 = 6000.0
    int_0 = module_0.award_points(float_0, float_1)
    assert int_0 == 20
    assert module_0.VIP_THRESHOLD_PLN == 5000
    assert module_0.POINTS_CAP == 5000


def test_case_4():
    float_0 = 60000.0
    float_1 = 10000.0
    int_0 = module_0.award_points(float_0, float_1)
    assert int_0 == 5000
    assert module_0.VIP_THRESHOLD_PLN == 5000
