# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import invoice as module_0


def test_case_0():
    str_0 = "FV/2,220000"
    with pytest.raises(ValueError):
        module_0.parse_invoice_id(str_0)


def test_case_1():
    str_0 = "FV/1999/12/1234"
    with pytest.raises(ValueError):
        module_0.parse_invoice_id(str_0)


def test_case_2():
    str_0 = "   FV/2021/01/00v0   "
    with pytest.raises(ValueError):
        module_0.parse_invoice_id(str_0)


def test_case_3():
    str_0 = "F@i+SCh3/K0:"
    with pytest.raises(ValueError):
        module_0.parse_invoice_id(str_0)


def test_case_4():
    str_0 = "FV/2101/01/1234"
    with pytest.raises(ValueError):
        module_0.parse_invoice_id(str_0)
